export enum types {
  SET_LOADING_STATUS = "SET_LOADING_STATUS",
  SET_ERROR_STATUS = "SET_ERROR_STATUS",
  SET_CURRENT_WEATHER = "SET_CURRENT_WEATHER",
  SET_DAILY_WEATHER = "SET_DAILY_WEATHER",
  SET_TIMEZONE = "SET_TIMEZONE"
}
